### ISSUE TITLE
Using binary packages in CI

### ISSUE THREAD

**Issue by Lupus** [OCamlPro/opam-bin#24]
I'm trying to adopt opam-bin in CI environment. I have a service, which holds the repo data, providing http access and rsync access. My CI job is adding http binary repo to the switch, builds stuff and then runs `opam-bin push --merge` and triggers rebuild of opam repo index. Judging by build time, binary packages are not used during installation of packages to the switch. I've tried reproducing this locally, and it runs way faster, but locally I have local repo populated with packages, while in CI I expect opam-bin to fetch stuff from http url. Is that a fair expectation, or `opam-bin pull` is required first?

**Comment by lefessan** [comment]
`opam-bin` lookups for binary packages in all repositories, so normally, you don't need to `opam-bin pull` before, since `opam` will download the index of the binary repo.
I think version 0.95 generates two log files to help debugging: `$HOME/.opam/plugins/opam-bin/opam-bin.info` and `$HOME/.opam/plugins/opam-bin/opam-bin.log`. Maybe you can ask your CI to display them on completion ? (the .info file should be very short, one line per package, the .log is much more verbose) That would help a lot to understand the problem.

**Comment by Lupus** [comment]
Logs indeed helped a lot, thanks for the tip! I was using wrong opam root and binary packages were not even created. After I fixed this, binary packages indeed start to be picked up from http binary repo.
