### ISSUE TITLE
Multiple occurences of files within tarballs

### ISSUE THREAD

**Issue by Lupus** [OCamlPro/opam-bin#27]
I've glanced at what's inside the tarballs created by opam-bin (mostly out of curiosity) and noticed that some files are preset two or more times. I've checked couple tarballs and here are the stats for the number of occurences:

```
$ tar -tf core.v0.13.0+bin+294211e5+a1fbfcb4-bin.tar.gz | sort | uniq -c | cut -d" " -f7 | sort | uniq -c
      8 1
    189 2
    182 3

$ tar -tf core_kernel.v0.13.1+bin+480ab941+ff9b8e3e-bin.tar.gz | sort | uniq -c | cut -d" " -f7 | sort | uniq -c
      4 1
    980 2
    470 3
```

It seems that `opam-bin` adds files multiple times? That increases file sizes and disk IO as tar is unpacking those one after another according to the documentation.

**Comment by lefessan** [comment]
Thanks for noticing this problem! Indeed, `opam` provides the list of installed files, but the list includes directories. So, when `opam-bin` calls `tar`, files were added several times, once directly, and everytime an upper directory is given.

It should be fixed in this PR, that removes directories from the list of installed files when calling `tar`:
https://github.com/OCamlPro/opam-bin/pull/28

**Comment by Lupus** [comment]
Just upgraded our CI to use latest master. I can confirm that new tarballs do not have duplicate entries, but looks like tar was smart enough to not include the contents twice... File sizes are exactly the same as before the fix. I was hoping for them to becone 30% of original size :smile: 

Thanks for quick fix @lefessan !
